Perform the following operations using R/Python on suitable data sets:

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
#import data
sales = pd.read_excel("/content/supermarket_sales.xlsx")
sales.describe()

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,0.000000,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905,49.650000,10.00000

In [ ]:
sale1 = pd.read_csv("/content/Heart.csv")
sale1.describe()

,Unnamed: 0,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000
mean,152.000000,54.438944,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241
std,87.612784,9.038662,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438
min,1.000000,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,76.500000,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,152.000000,56.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,227.500000,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,303.000000,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000

In [ ]:
#indexing and selecting
#using Col names,.loc and .iloc
sale1[["Age","Sex"]]

     Age  Sex
0     63    1
1     67    1
2     67    1
3     37    1
4     41    0
..   ...  ...
298   45    1
299   68    1
300   57    1
301   57    0
302   38    1

[303 rows x 2 columns]

In [ ]:
sales.loc[301]

Invoice ID                         181-82-6255
Branch                                       B
City                                  Mandalay
Customer type                           Normal
Gender                                  Female
Product line                Home_and_lifestyle
Unit price                               16.37
Quantity                                     6
Tax 5%                                   4.911
Total                                  103.131
Date                       2019-08-02 00:00:00
Time                                  10:58:00
Payment                                   Cash
cogs                                     98.22
gross margin percentage               4.761905
gross income                             4.911
Rating                                     7.0
Name: 301, dtype: object

In [ ]:
sales

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,692-92-5582,B,Mandalay,Member,Female,Food_and_beverages,54.84,3,8.226,172.746,2/20/2019,13:27:00,Credit card,164.52,4.761905,8.226,5.9
1,351-62-0822,B,Mandalay,Member,Female,Fashion_accessories,14.48,4,2.896,60.816,2019-06-02 00:00:00,18:07:00,Ewallet,57.92,4.761905,2.896,4.5
2,529-56-3974,B,Mandalay,Member,Male,Electronic_accessories,25.51,4,5.102,107.142,2019-09-03 00:00:00,17:03:00,Cash,102.04,4.761905,5.102,6.8
3,299-46-1805,B,Mandalay,Member,Female,Sports_and_travel,93.72,6,28.116,590.436,1/15/2019,16:19:00,Cash,562.32,4.761905,28.116,4.5
4,319-50-3348,B,Mandalay,Normal,Female,Home_and_lifestyle,40.30,2,4.030,84.630,2019-11-03 00:00:00,15:30:00,Ewallet,80.60,4.761905,4.030,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,886-18-2897,A,Yangon,Normal,Female,Food_and_beverages,56.56,5,14.140,296.940,3/22/2019,19:06:00,Credit card,282.80,4.761905,14.140,4.5
996,745-74-0715,A,Yangon,Normal,Male,Electronic_accessories,58.03,2,5.803,121.863,2019-10-03 00:00:00,20:46:00,Ewallet,116.06,4.761905,5.803,8.8
997,727-02-1313,A,Yangon,Member,Male,Food_and_beverages,31.84,1,1.592,33.432,2019-09-02 00:00:00,13:22:00,Cash,31.84,4.761905,1.592,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home_and_lifestyle,65.82,1,3.291,69.111,2/22/2019,15:33:00,Cash,65.82,4.761905,3.291,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion_accessories,88.34,7,30.919,649.299,2/18/2019,13:28:00,Cash,618.38,4.761905,30.919,6.6

In [ ]:
sales.iloc[0:4,5:7]

             Product line  Unit price
0      Food_and_beverages       54.84
1     Fashion_accessories       14.48
2  Electronic_accessories       25.51
3       Sports_and_travel       93.72

In [ ]:
# x = np.array(sale1)
# df = pd.DataFrame(x)
sale1.sort_values(by=["Age"])

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
132,133,29,1,nontypical,130,204,0,2,202,0,0.0,1,0.0,normal,No
101,102,34,1,typical,118,182,0,2,174,0,0.0,1,0.0,normal,No
225,226,34,0,nontypical,118,210,0,0,192,0,0.7,1,0.0,normal,No
283,284,35,1,nontypical,122,192,0,0,174,0,0.0,1,0.0,normal,No
117,118,35,0,asymptomatic,138,183,0,0,182,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,43,71,0,nontypical,160,302,0,0,162,0,0.4,1,2.0,normal,No
103,104,71,0,nonanginal,110,265,1,2,130,0,0.0,1,1.0,normal,No
233,234,74,0,nontypical,120,269,0,2,121,1,0.2,1,1.0,normal,No
257,258,76,0,nonanginal,140,197,0,1,116,0,1.1,2,0.0,normal,No
161,162,77,1,asymptomatic,125,304,0,2,162,1,0.0,1,3.0,normal,Yes

In [ ]:
sale1.describe()

,Unnamed: 0,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000
mean,152.000000,54.438944,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241
std,87.612784,9.038662,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438
min,1.000000,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,76.500000,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,152.000000,56.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,227.500000,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,303.000000,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000

In [ ]:
sale1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  303 non-null    int64
 1   Age         303 non-null    int64
 2   Sex         303 non-null    int64
 3   ChestPain   303 non-null    object
 4   RestBP      303 non-null    int64
 5   Chol        303 non-null    int64
 6   Fbs         303 non-null    int64
 7   RestECG     303 non-null    int64
 8   MaxHR       303 non-null    int64
 9   ExAng       303 non-null    int64
 10  Oldpeak     303 non-null    float64
 11  Slope       303 non-null    int64
 12  Ca          299 non-null    float64
 13  Thal        301 non-null    object
 14  AHD         303 non-null    object
dtypes: float64(2), int64(10), object(3)
memory usage: 35.6+ KB

Unique Elements

In [ ]:
sale1["ChestPain"].value_counts()

asymptomatic    144
nonanginal       86
nontypical       50
typical          23
Name: ChestPain, dtype: int64

In [ ]:
#identifying missing values and fill in the missing values
sale1.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [ ]:
sale1.fillna("Zer0",inplace=True)
sale1.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          0
AHD           0
dtype: int64

In [ ]:
#format
sale1.style.format({"RestBP":"BP:{}"})